### ISSUE TITLE
Doesn't support 3440x1440

### ISSUE THREAD

**Issue by InfernalPlacebo** [NiHoel/Anno1800UXEnhancer#1]
Hi there, I have an Ultra-Wide monitor doing 3440x1440 display. Due to the resolution the reader is not able to detect my statistics. When I scale down my resolution to 2560x1440 it works fine. Unfortunately, changing it lower makes the game look odd an stretched on my display. Is there a way we can add support for this resolution?

I know a little C#/C++ so I am willing to help if you need me to do something or test or whatever. I can also supply whatever information about my game/client/system you need.

**Comment by Gersdorff** [comment]
Hallo,

try this first.

https://github.com/Dejauxvue/AnnoCalculatorServer/blob/master/README.md#more-resultions

**Comment by InfernalPlacebo** [comment]
Still getting the error, it seems like it isn't detecting my resolution correctly.
![Snag_e874c23](https://user-images.githubusercontent.com/37945395/78508946-d188ac80-7747-11ea-8885-286611cd7148.png)

**Comment by InfernalPlacebo** [comment]
@Gersdorff is there any update for this? :)

**Comment by Gersdorff** [comment]
Sorry, but I'm not the developer. I can offer you otherwise, this as an attempt to solve. 

https://github.com/Dejauxvue/AnnoCalculatorServer/issues/2#issuecomment-524551618

**Comment by InfernalPlacebo** [comment]
Oh, I totally thought you were, my bad!

**Comment by NiHoel** [comment]
Can you send me some screenshots how the statistics screen looks like on 3440x1440?

The resolutions in image_recon are only necessery to detect the population from the HUD menu.
The statistics menu is handeled using relative positions. If you have at assets/test_screenshots you see how elements are layout on normal 16:9 screens. If this deviates on your screen, it causes the program to not detect it.

**Comment by InfernalPlacebo** [comment]
Here is my statistics screen.

![image](https://user-images.githubusercontent.com/37945395/79930515-f5b1e200-8405-11ea-989d-ba41dbf9c611.png)
