### ISSUE TITLE
Server stops after a few minutes

### ISSUE THREAD

**Issue by Electroblade** [NiHoel/Anno1800UXEnhancer#10]
The server runs fine for some time and then all of a sudden stops. I then close it and reopen it and then it will update the calculator again for a time and then stops again.

Thanks for all your hard work.

**Comment by NiHoel** [comment]
Please start it in verbose mode, wait for the crash, and send me all the files. See section "If you encounter any buy ..." in the Readme.

**Comment by Electroblade** [comment]
I have downloaded the server again and I am running it in verbose mode. It has been running for 8hrs now and its still fine.
Thanks.
