### ISSUE TITLE
Running Calculator with Geforce Now

### ISSUE THREAD

**Issue by Fluxxa** [NiHoel/Anno1800UXEnhancer#11]
I'm using GeForce Now to run Anno. Is there a possibility to get it to work?
Is just says "Anno 1800 window not found"

**Comment by Fluxxa** [comment]
Thanks for the quick answer.
Now i get another error

![Unbenannt](https://user-images.githubusercontent.com/74040676/98440739-c7be9180-20fa-11eb-827c-cf7bbaf70964.JPG)

I'm running it on my Surface with max. resolution 2736x1824 and the resolution of the game is 1920x1200 if that helps

**Comment by NiHoel** [comment]
Can you make two screenshots with global and island population open, as shown here: https://github.com/NiHoel/Anno1800UXEnhancer/blob/master/instructions_0.png

Please set Ubisoft Connect to store .png
![grafik](https://user-images.githubusercontent.com/28017252/98443004-d613aa00-2108-11eb-8e87-d7289a351e18.png)

and use F12 to take the screenshots.


The server works fine despite the error. The only thing that won't work is extracting the population number from the HUD pop up.

**Comment by Fluxxa** [comment]
I don't use the Ubisoft Connect. I just login with GeForce Now, so there I can't change anything.
GeForce Now always starts in full screen mode (2736x1824) and I can't change that. The game runs in 1920x1200 but it is not shown in the picture because it's like a remote control.
![1](https://user-images.githubusercontent.com/74040676/98446347-314f9780-211d-11eb-8751-9d6327ae812e.png)
![3](https://user-images.githubusercontent.com/74040676/98446453-d4a0ac80-211d-11eb-83f6-7c164786fc36.png)

**Comment by NiHoel** [comment]
Redownload the image_recon folder from the link above.

**Comment by Fluxxa** [comment]
I just gave it a quick try, and it works! Great job!
Thanks you so much for the super quick support. I'll get in touch when I tried the UXEnhancer
