### ISSUE TITLE
Server closes

### ISSUE THREAD

**Issue by CrysK** [NiHoel/Anno1800UXEnhancer#13]
I start the game, open the html file and then start the 'Server.exe', but it stoping immediately:
```
PS ~\UXEnhancer> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=german
Update tesseract language german

PS ~\UXEnhancer>
```

![statistics_screenshot](https://user-images.githubusercontent.com/43782371/101661272-6450b800-3a48-11eb-97c7-b515d3d3168a.png)

All is up to date. It's the first time I played with the latest DLC (lions). The older version of the tool (v4) worked solide.

**Comment by NiHoel** [comment]
Does this always happen or only if the statistics screen is open?

**Comment by CrysK** [comment]
Thanks for the very quick answer.

This really always happens. Whether Anno is started or not, no matter in which menu I am in Anno or whether I have the website open or not. The `Server.exe` always closes in the same way.

I have already tested version 5.0 and 5.1, there the same. With my old version (4.1) it always shows `request received: lang=german` (as it should be). But no more data is transferred to the website.

From another location e.g. `c:\UW\Server.exe` I have already tested it without success.

**Comment by NiHoel** [comment]
What is the output if Anno is not open?

**Comment by CrysK** [comment]
```
PS ~\UXEnhancer> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Unknown exception

PS ~\UXEnhancer>
```

**Comment by NiHoel** [comment]
What confuses me is that

Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.

is printed when Anno is open but not in the other case.

**Comment by NiHoel** [comment]
After you have tested the UXEnhancer.exe, can you please restart your computer and see if it still crashes.

**Comment by CrysK** [comment]
I just did that and restarted, if I now start Server.exe without the Anno started, that comes:
```
PS ~\UXEnhancer> .\Server.exe
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=german
Anno 1800 window not found
Couldn't take screenshot
request received: lang=german
Anno 1800 window not found
Couldn't take screenshot
[...]

PS ~\UXEnhancer> ^C
```
Maybe I still had the old v4.1 Server.exe running parallel before.

If I start the UXEnhancer.exe (no matter if Anno is open or not) this is what happens:
```
PS ~\UXEnhancer> .\UXEnhancer.exe -v
Initializing ... Load sessions and regions.
Load factories.
Version up to date.
Load population levels.
Load texts.
Update tesseract language german
Done

PS ~\UXEnhancer> .\UXEnhancer.exe -v
Initializing ... Load sessions and regions.
Load factories.
Version up to date.
Load population levels.
Load texts.
Update tesseract language german
Done
[20:13:1.225604] Trader: 0, ship full: 1, has reroll button: 0

PS ~\UXEnhancer>
```
You can see the window from time to time, but it also closes by itself.

I have two monitors with the same resolution (2560x1440), if I connect only one, the same thing happens.

I downloaded Anno from the UbiStore again, nothing has changed. There are no mods installed.

**Comment by CrysK** [comment]
I got it! 🥳
If you set the language (in Anno and the website) to English, everything works perfectly! 

If you don't run the website, it will start from english and will also output values from time to time, where Server.exe -v

The funny thing is that the `Server.exe` and `UXEnhancer.exe` terminate. Without error message ... 

I would like to continue playing in German, is there anything you can do? ;)

**Comment by NiHoel** [comment]
It's hard to debug an error I cannot reproduce on my site. 
I might add some debug code and send you a new version at the weekend.

**Comment by CrysK** [comment]
Thanks, that would be great. I just tested all other possible languages (spanish, french, ...) and there exactly the same as in german:
if you change the language on the website to something else like english, the Server.exe will be killed immediately afterwards. No difference if Anno is running or not.

**Comment by NiHoel** [comment]
Test the following version with the option -v and send me the console output and the debug_images folder:

https://drive.google.com/drive/folders/1Vsy3kXGe11d28pISqR82VpaCGdZaNtyi?usp=sharing

You only need to update the files from the main folder.

**Comment by CrysK** [comment]
Thank you. First I started Anno7 and the Website, than the UXEnhancer. Then I changed the language on the Website from english to german. Then the UXEnhancer crashes. I restarted the UXEnhancer and it crashes immediately again.
```
\UXEnhancer_v>Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=english
Process image
Update tesseract language english
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: detected resolution: 2560x1440
can't find population
All Islands
Update OCR
Detect words
request received: lang=english
Process image
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: can't find population
All Islands
Update OCR
Detect words
request received: lang=english
Process image
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: can't find population
All Islands
Update OCR
Detect words
request received: lang=english
Process image
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: can't find population
All Islands
Update OCR
Detect words
request received: lang=english
Process image
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: can't find population
All Islands
Update OCR
Detect words
request received: lang=english
Process image
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: can't find population
All Islands
Update OCR
Detect words
request received: lang=english
Process image
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Split string

Island: can't find population
All Islands
Update OCR
Detect words
request received: lang=german
Process image
Update tesseract language german
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words

\UXEnhancer_v>Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=german
Process image
Update tesseract language german
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words

\UXEnhancer_v>
```

All 12 files from the debug_images folder:

![icon_template](https://user-images.githubusercontent.com/43782371/101991639-6f0c8680-3cae-11eb-8f7c-da8439ce1067.png)
![pop_popup](https://user-images.githubusercontent.com/43782371/101991640-703db380-3cae-11eb-906b-9d06ff41239e.png)
![screenshot-0](https://user-images.githubusercontent.com/43782371/101991642-703db380-3cae-11eb-85e5-45ce3da4a470.png)
![screenshot-1](https://user-images.githubusercontent.com/43782371/101991643-72077700-3cae-11eb-8c33-d825d575217f.png)
![screenshot-2](https://user-images.githubusercontent.com/43782371/101991644-75026780-3cae-11eb-9e16-90927825ef79.png)
![screenshot-3](https://user-images.githubusercontent.com/43782371/101991645-77fd5800-3cae-11eb-8e19-96417df81fbf.png)
![screenshot-4](https://user-images.githubusercontent.com/43782371/101991649-7af84880-3cae-11eb-956e-0d0a36b2ab4b.png)
![screenshot-5](https://user-images.githubusercontent.com/43782371/101991651-7d5aa280-3cae-11eb-8865-9ec8993080a3.png)
![screenshot-6](https://user-images.githubusercontent.com/43782371/101991653-80559300-3cae-11eb-9f2f-22f8d799e876.png)
![screenshot-7](https://user-images.githubusercontent.com/43782371/101991655-83508380-3cae-11eb-8224-e6267e8315e0.png)
![statistics_screenshot](https://user-images.githubusercontent.com/43782371/101991657-864b7400-3cae-11eb-95ce-e4a3e6c261cd.png)
![statistics_text](https://user-images.githubusercontent.com/43782371/101991658-877ca100-3cae-11eb-8300-ab1400dc5030.png)

**Comment by NiHoel** [comment]
I nailed the crash down to a few lines of code. Please try this version:

https://drive.google.com/drive/folders/1jb6OwqiKnDLpoEm2ibCJy3PelKK1-zB3?usp=sharing

**Comment by NiHoel** [comment]
Try this one again, I updated the files:

https://drive.google.com/drive/folders/1Vsy3kXGe11d28pISqR82VpaCGdZaNtyi?usp=sharing

**Comment by CrysK** [comment]
Thank you. But still not working 😬

```
PS ~\UXEnhancer_deb> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=german
Process image
Update tesseract language german
Crop image
Detect 'statistics'
Put in dictionary 22438
Update OCR
Detect words
Set page mode
Set image data
Recognize
PS ~\UXEnhancer_deb>
```

**Comment by NiHoel** [comment]
Then the crash is somewhere in the Tesseract process. I don't think there is much I can do about it without being able to debug it.

**Comment by CrysK** [comment]
Too bad, but thanks for your effort anyway. Is there anything else I can do?

**Comment by Peccadilloz** [comment]
Just wanted to let you know that I have a similar issue, although unlike CrysK i was not able to resolve it by changing the language of the tool and Anno itself to english. When Anno is running, the following is printed in the command window which then closes itself afterwards:

Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=english

I have tried your suggestions from above but none worked for me.

**Comment by CrysK** [comment]
I would like to reconstruct the error on another PC. To do this, I wanted to have the UXEnhancer server evaluate a screenshot (in German, English, ...) on another PC. Unfortunately I can't get the UXEnhancer server to recognize the screen shot. Is there a tutorial for this?

**Comment by NiHoel** [comment]
I uploaded a ServerD.exe here: https://drive.google.com/file/d/1WFpVhOnwVx7XAeGHW75XJSlTFGnfWv5R/view?usp=sharing

You can pass the path to a screenshot as a command line argument.

The alternative way using the normal server is a bit tricky. You need to have an application open named "Anno 1800" (in full screen and focused). A way to achieve that. Open the screenshot in fullscreen, open a folder named Anno 1800 in the explorer and make it fill the screen (the server will assume that this is the Anno window). Then start the server and make the explorer to be in front. Hover over the application in the taskbar that shows the screenshot. By doing so, the explorer is still on focus, but the actual screen shows the screenshot. The server will then capture the screenshot and process it.

**Comment by CrysK** [comment]
Thanks for the instructions, that I will test sone.

But in your link is only a "reader.lib" included, no binary.

**Comment by NiHoel** [comment]
This is the correct link: https://drive.google.com/drive/folders/1jb6OwqiKnDLpoEm2ibCJy3PelKK1-zB3?usp=sharing

**Comment by CrysK** [comment]
I tested everything possible on my work laptop today. There is (almost) nothing game related installed.

There everything works great, just the same files that I have on my gaming PC.
The workaround with the fullscreen explorer window I already tried and that never works for me. I wrote a small program that creates an empty fullscreen window with the title "Anno 1800":
https://cloud8.eu/s/S4RNNeycJjd4ZBY
With this I could test the regular version on any language. 

I think it's definitely my PC. Are any resources being used that I may have uninstalled? Because it's strange that it only works in English, not in any other language.

It's not the browser either. I have tested Firefox, Safari, Chrome and Edge.

**Comment by NiHoel** [comment]
It has nothing to do with the browser or calculator. You could even issue requests by entering http://localhost:8000/AnnoServer/Population into the URL bar of the browser. This generates a standard HTML request.

Frankly, I have no idea what software might interfere. Apart from vcredist all components are shipped with the zip file.

**Comment by NiHoel** [comment]
If you have Visual Studio, you can try to debug the application. I uploaded the dlls and exe in the debug version together with the symbol files: https://drive.google.com/drive/folders/1jb6OwqiKnDLpoEm2ibCJy3PelKK1-zB3?usp=sharing

**Comment by CrysK** [comment]
@NiHoel I do not know why, but now the server is running 🥳.
The version of 23. and 24.01. run with me. I'm not quite sure anymore if I had tested the version from the 23rd, because now (also with the last version) the startup takes very long (about 1min), but then everything runs, in all languages on all my devices.
All other versions still will not run (on my PC).

I also tried to compile and debug my own version, but because I never worked with Visual Studio before, I didn't get that done: `<build cpp/visual studio/UXEnhancer.sln>` here I'm not clear what to run and what to do. The previous steps went through without errors. 
If you have time, you can explain me, just for interest.

But thanks for tool and your support 👍

**Comment by NiHoel** [comment]
I'm glad that it works now.
The startup takes so long because it loads many files from the drive. You may put it onto SSD.

<build cpp/visual studio/UXEnhancer.sln> is not a command. It means that you should open the Visual Studio project.

**Comment by CrysK** [comment]
> The startup takes so long because it loads many files from the drive. You may put it onto SSD.
I have a PCIe M.2 SSD ;)
But the load during startup is minimal: CPU <10%, SSD, <0.1MB/s (according to Taskmanager).

> <build cpp/visual studio/UXEnhancer.sln> is not a command. It means that you should open the Visual Studio project.
I installed Visual Studio 2019, started the `UXEnhancer.sln` with it and then clicked debugging (F5). Then comes an error that the Server.exe is not present ...

**Comment by CrysK** [comment]
The UXEnhancer unfortunately takes a very very long time to evaluate the images. At first I thought it was because of my big Anno world, but even if Anno is closed and I only analyze a screenshot, the tool needs 1-2min to completely analyze e.g. the population. It is loaded piece by piece. The tool does not generate any load, the debug mode is also not on.

**Comment by NiHoel** [comment]
What do you mean "it is loaded piece by piece"? How do you notice that?

Taking 1-2 min to analyze an image is really odd. Is it faster if you analyze a second one right after the first one?

If not, I have only one possible explanation. Maybe one of the libraries is waiting for an external event before it continues. Otherwise, I have no explanation why my code takes so long on a normal computer.

**Comment by CrysK** [comment]
> What do you mean "it is loaded piece by piece"? How do you notice that it is not only one step that takes ages but every sub-step takes much longer?

You are right, I had seen that wrong. The data of an image are always loaded simultaneously.
> Taking 1-2 min to analyze an image is really odd. Is it faster if you analyze a second one right after the first one?

Ok, that was a bit exaggerated. Starting the tool takes about 30s and loading a single image takes about 5-30s. But I never know when it takes the screenshot. Every now and then I press reset in the web interface and click on the next image, but it still loads the data from the old image (5-15s later). The population usually takes 5-15s the buildings 15-30s. Whether loading the same image twice is faster I don't know. Subjectively it takes the same time.

**Comment by JerjerBinks** [comment]
Hello,
I continue on this thread because my issue is that Server.exe crashes after a few lines.
I launched it in verbose mode to upload the log and here it is. (the first line and the last lines).
It might be an issue of non-relative path ? 
![Capture d'écran 2021-03-11 08 51 24](https://user-images.githubusercontent.com/20711914/110754544-3eee6880-8248-11eb-9890-bcc5001506c9.png)
![Capture d'écran 2021-03-11 08 59 44](https://user-images.githubusercontent.com/20711914/110754552-401f9580-8248-11eb-974f-706c8f398809.png)

**Comment by JerjerBinks** [comment]
I tried the 5.0 version, the log is much shorter but crashes anyway, also I launched it from the same disk where the game is installed (F:) :

PS F:\Tools\Anno1800UXEnhancer_v5.0> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=french
Update tesseract.
PS F:\Tools\Anno1800UXEnhancer_v5.0>

**Comment by JerjerBinks** [comment]
I then launched the 5.3 again but on the same disk where the game is installed (F:) and same result (except last tesseract line) than 5.0:

PS F:\Tools\Anno1800UXEnhancer_v5.3> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=french
Update tesseract language french
PS F:\Tools\Anno1800UXEnhancer_v5.3>

**Comment by NiHoel** [comment]
Neither the absolute paths nor the errors you see are the problem. The crash happens inside the text recognition library. I am not in control of what happens there nor can I reproduce this behavior. Therefore, I couldn't fix it so far.

You may try to change the language to English.

**Comment by JerjerBinks** [comment]
I changed to english, in game and in the html:

PS F:\Tools\Anno1800UXEnhancer_v5.3> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=english
Update tesseract language english
PS F:\Tools\Anno1800UXEnhancer_v5.3>

**Comment by NiHoel** [comment]
@JerjerBinks Do you have time this evening to test something?

**Comment by JerjerBinks** [comment]
I will try !

**Comment by NiHoel** [comment]
What is your CPU?

**Comment by JerjerBinks** [comment]
My cpu is a I5 750 (2010 gen).

**Comment by NiHoel** [comment]
Try this version: https://drive.google.com/file/d/1gP6xM5379P5_ZQ-g2gIDja53t8q5kV54/view?usp=sharing

**Comment by JerjerBinks** [comment]
I replaced the zlib1.dll (you wrote "files" but the link made me download only one file) and still same behavior:

PS F:\Tools\Anno1800UXEnhancer_v5.3> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
request received: lang=english
Press ENTER to exit.
Update tesseract language english
PS F:\Tools\Anno1800UXEnhancer_v5.3>

Thank you for your time. I really hope this will finally work because your extraction feature looks so amazing I want to use it :)

**Comment by NiHoel** [comment]
wrong link, this is the correct one: https://drive.google.com/drive/folders/1Vsy3kXGe11d28pISqR82VpaCGdZaNtyi?usp=sharing

**Comment by JerjerBinks** [comment]
Ok thanks I will try tomorrow morning (11pm here).

**Comment by JerjerBinks** [comment]
It works perfectly ! Thank you !

**Comment by NiHoel** [comment]
Can you try one more thing, to ease maintaining this fix:
Use all the files from the v5.3 release except for the reader.lib (Use the one from the link above). Check whether it still works.

**Comment by JerjerBinks** [comment]
I tried the 5.3 with the new reader.lib but it doesn't work (same as before).
I also tried with the new zlib1.dll (in case) but doesn't work either.

**Comment by NiHoel** [comment]
@CrysK @Peccadilloz 
I finally found the solution. Download the current release and extract all files. Then download Anno1800UXEnhancer_v5.3_fallback.zip and replace the files.

Background: Tesseract (used for text recognition) uses special [AVX ](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) instructions for computing. On older CPUs, these aren't available, therefore the program crashes. I now recompiled tesseract without AVX. The consequence is that it runs on older CPUs but its 2x slower.

Thanks for all your effort to find the solution!

**Comment by JerjerBinks** [comment]
Thank you for your support !

**Comment by CrysK** [comment]
Thank you very much @NiHoel
The v5.3_fallback version also solved my problem!

I actually have an i7-3770K CPU on my main PC as well, and a Pentium 4415Y or i5-7200U CPU on the (slower) laptops, on which the other version goes.
It didn't dawn on me that it was due to the CPU itself. As I am also 100% sure that it ran earlier (on the same hardware).

Loading an image takes about 2-3 seconds, that's not much and when updating the population also bearable, but with the goods passes there already some time, because you also do not know exactly when was updated. But I already have an idea and would open a new issue. 

Thanks for your support! Have a nice weekend and stay healthy.

**Comment by Peccadilloz** [comment]
> 



> 

Where exactly do i find this fallback version?

**Comment by NiHoel** [comment]
https://github.com/NiHoel/Anno1800UXEnhancer/releases/download/v9.0/Anno1800UXEnhancer_v9.0_fallback.zip

It's linked below the normal zip archive on the releases page.
