### ISSUE TITLE
Consumer goods relative to population thresholds

### ISSUE THREAD

**Issue by JerjerBinks** [NiHoel/Anno1800UXEnhancer#15]
Hi,

New topic now that everything works fine :)

I noticed that, for example, as soon as there is 1 worker present, all the consumer goods appear to be needed.
But there are thresholds for the necessity of the different types of goods.
Here is a picture with only 220 Workers and already a need for brewery ! It is misleading because the need of brewery begins at 500 Workers.
I tried also with 30 farmers on an island, the need for fish, shnapps and clothes appear although they don't need anything at this population.
It also tells me that I need a workforce of 165 farmers although I don't except if I want to have all needs supplied for all population.
Is it a way to avoid negative economic balance for each island? 

![image](https://user-images.githubusercontent.com/20711914/110922756-5ef15b00-8320-11eb-9deb-9626c1e0dbbd.png)

![image](https://user-images.githubusercontent.com/20711914/110922834-7af4fc80-8320-11eb-8efe-91ca95cb7593.png)

**Comment by NiHoel** [comment]
![grafik](https://user-images.githubusercontent.com/28017252/110923380-22722f00-8321-11eb-9ba8-98930004f159.png)

I don't understand what you mean by "It also tells me that I need a workforce of 165 farmers although I don't except if I want to have all needs supplied for all population.
Is it a way to avoid negative economic balance for each island?"

**Comment by JerjerBinks** [comment]
Ok for the option, I didn't see it, nice !
The Required Workforce is now correct thanks to the disappearance of the needs and their production buildings.

I close the topic, thank you again.
