### ISSUE TITLE
Wrong production chain for Soap Factory

### ISSUE THREAD

**Issue by Wunderharke** [NiHoel/Anno1800UXEnhancer#17]
Really great project! Except for occasional difficulties with the island recognition, the program works great and saves a lot of work! However, since I recently started to enter the entire production chain, I noticed that apparently a wrong recipe is used for the soap production.
According to [fandom wiki](https://anno1800.fandom.com/wiki/Soap_Factory) the chain for soap is 2 -> 2 -> 1, but implemented is 1 -> 1 ->.

**Comment by NiHoel** [comment]
The calculator the number of buildings you require. This is not necessarily a full production chain.

**Comment by Wunderharke** [comment]
Ahh all right maybe then a display of overproduction would be nice?

**Comment by NiHoel** [comment]
![grafik](https://user-images.githubusercontent.com/28017252/111646928-5c03d800-8802-11eb-9416-9a22fa131eba.png)
![grafik](https://user-images.githubusercontent.com/28017252/111647113-7fc71e00-8802-11eb-9243-2fa1ed937566.png)
