### ISSUE TITLE
It wont update anything

### ISSUE THREAD

**Issue by MystixBlack** [NiHoel/Anno1800UXEnhancer#2]
Heyo i need some help here please :/,

So i have both the Enhanced and the Calculator on my Pc. and followed the ReadMe instructions. but it dosnt seem to work. the server only writes what you see in the picture.

![Unbenannt](https://user-images.githubusercontent.com/63278265/78631831-9e583180-789d-11ea-8759-c147792a23f5.JPG)

i play on 3840x2160 and tried fullscreen and borderless. i have both the game and the Calculator set on german.

is there a fix for this ? or is this not working rn bc of the recent update dlc 

cheers Mystix

**Comment by MystixBlack** [comment]
btw the picture is from my try when i had both set to englisch. before it did the same with lang=german.

**Comment by gatsbys** [comment]
Same here :(

**Comment by NiHoel** [comment]
Did you try it via HUD or statistics menu. 

Also have a look at this: https://github.com/NiHoel/Anno1800UXEnhancer/issues/1#issuecomment-616188898

**Comment by MystixBlack** [comment]
I am in the statistics menu.
when i run the dserver it only shows this: 
![Unbenannt](https://user-images.githubusercontent.com/63278265/79792274-e6239200-834e-11ea-86cf-9d1d4711b7c8.JPG)

and creates 3 debug icons into the debug_images folder:

![icon_gray](https://user-images.githubusercontent.com/63278265/79792342-05222400-834f-11ea-91d1-c6ed5e13482e.png)
![icon_shilouette](https://user-images.githubusercontent.com/63278265/79792345-05baba80-834f-11ea-8a48-fe1c61db90f0.png)
![icon_template](https://user-images.githubusercontent.com/63278265/79792346-05baba80-834f-11ea-86ea-7772e13d49be.png)

**Comment by NiHoel** [comment]
When you open the website, it does not trigger "request received"?

**Comment by MystixBlack** [comment]
now i got further: 
![Unbenannt](https://user-images.githubusercontent.com/63278265/79793412-cf7e3a80-8350-11ea-8d60-165ea682bf8a.JPG)

and it also made more pngs to the debug folder.:
![island_name_minimap](https://user-images.githubusercontent.com/63278265/79793483-ef156300-8350-11ea-9a41-e69bdbdf8071.png)
![pop_popup](https://user-images.githubusercontent.com/63278265/79793524-048a8d00-8351-11ea-81eb-92fee4cb4f29.png)
![screenshot](https://user-images.githubusercontent.com/63278265/79793527-048a8d00-8351-11ea-8371-aeb58edda133.png)
![statistics_text](https://user-images.githubusercontent.com/63278265/79793529-05bbba00-8351-11ea-83a9-8b88f0c36358.png)
![text_img](https://user-images.githubusercontent.com/63278265/79793530-05bbba00-8351-11ea-85c9-d04ba20e40ff.png)


this is my statistic screen:
![Anno 18002020-4-20-21-39-53](https://user-images.githubusercontent.com/63278265/79793578-18ce8a00-8351-11ea-8a18-26d85a44d31a.jpg)
![Anno 18002020-4-20-21-40-2](https://user-images.githubusercontent.com/63278265/79793581-19672080-8351-11ea-94cc-854af83d6a9e.jpg)
![Anno 18002020-4-20-21-40-4](https://user-images.githubusercontent.com/63278265/79793582-19ffb700-8351-11ea-8fa9-a50a1c63ce84.jpg)
![Anno 18002020-4-20-21-40-6](https://user-images.githubusercontent.com/63278265/79793584-1a984d80-8351-11ea-979f-e03f57248162.jpg)

**Comment by NiHoel** [comment]
I assume the third one is screenshot.png
As you can see, it does not capture the whole screen. Most likely reason: Scaling in Windows is not set to 100%.
Windows does the scaling by lying to the program regarding its size. Therefore you only capture a portion instead of the whole.

**Comment by MystixBlack** [comment]
can i fix this without setting windows to 100% ? bc then everything would get way smaller for me and my desktop icons would scatter all over the place

**Comment by NiHoel** [comment]
You may try this:
https://github.com/Dejauxvue/AnnoCalculatorServer/issues/17#issuecomment-573304821

**Comment by NiHoel** [comment]
Would take me some time to implement DPI awareness.

**Comment by MystixBlack** [comment]
It dosnt capture the whole Screen while in have the Anno 1800 folder Open. But i have another workaround. I openes my game on my second Screen wich is 1980x1080 and of works there

**Comment by MystixBlack** [comment]
Thanks for the Help and if you find the time to implement dpi it would be great 😅 but it works for me now.
