### ISSUE TITLE
RerollBot doesn't actually click

### ISSUE THREAD

**Issue by bspendrin** [NiHoel/Anno1800UXEnhancer#21]
Dear NiHoel,
thank you for your amazing work on the Anno tools! (See below for the German version.)
I've encountered a problem with the reroll bot. I can start it, configure it correctly (at least I think that?), the clicker moves the coursor to the right position above the reroll button, but it doesn't click it.

The powershell output says "check reroll costs (internal: 0)", even though I've set "maxRerollCosts": "1000000" in the json config file. I've attached both my config and the powershell output.

What am I missing here? Sry for bothering you, I hope it isn't something completely stupid which I am just missing.
Thx for your help!
Benjamin

Und hier nochmal auf Deutsch (habe es mal auch auf Englisch gemacht, falls mal jemand nach so einem Fehler suchen sollte):
Ich hab ein Problem mit dem reroll bot. Ich starte ihn, stelle alles ein (welches Item, die maxRerollCosts), gehe ins Spiel, der reroll bot bewegt den Mauszeiger auch beim Händler über den richtigen Button zum würfeln - aber klickt dann nicht.

Der output der powershell -v ist "check reroll costs (internal: 0)", in der json config hab ich "maxRerollCosts": "1000000" stehen, kopiert aus dem manual. Ich hab mal beides angehängt.

Übersehe ich hier was? Ich hoffe, das ist nicht ein ganz blödes Ding wo ich einfach zu doof bin und etwas übersehe.
Danke für deine Hilfe und die tolle Arbeit an diesen Tools!
Benjamin
[UXEnhancerConfig.txt](https://github.com/NiHoel/Anno1800UXEnhancer/files/6888661/UXEnhancerConfig.txt)
[powershell_log.txt](https://github.com/NiHoel/Anno1800UXEnhancer/files/6888664/powershell_log.txt)

**Comment by NiHoel** [comment]
Please sent me  a screenshot where the reroll costs pop up is open.

**Comment by bspendrin** [comment]
Do you mean like this?

Screenshot from debug_images: ![screenshot-12](https://user-images.githubusercontent.com/77016519/127309283-d8d3fe83-9ab9-46b7-8f81-8ee999838267.png)
powershell screenshot: ![image](https://user-images.githubusercontent.com/77016519/127309444-1166a6cd-303c-46a1-bbf0-a2ffaad99dd4.png)

There is also this one from the image extraction process, maybe that helps as well?
![offerings](https://user-images.githubusercontent.com/77016519/127309681-f88ceed0-9e9e-4ac0-ab07-744cd9a22f10.png)

**Comment by NiHoel** [comment]
Try this version: https://drive.google.com/drive/folders/1Vsy3kXGe11d28pISqR82VpaCGdZaNtyi?usp=sharing

(only download and replace reader.lib, UXEnhancer.exe, Server.exe)

**Comment by bspendrin** [comment]
Thanks for the quick answer! It clicks now, but selects the wrong item.
Example: I selected the Erstklassiger Sappeur 190759 to buy, the bot correctly recognizes it to be there, clicks on the wrong item and thinks it bought the right one.
![image](https://user-images.githubusercontent.com/77016519/127370894-2c8303b6-8dbc-46d4-9076-80882c02a15f.png)
![Kopie (1) screenshot-0](https://user-images.githubusercontent.com/77016519/127370882-bf5b4ee0-66b6-4986-9a5f-f56411d1dd81.png)

Could that have something to do with the screen res (3440x1440)?

**Comment by NiHoel** [comment]
I updated the three files. Please update them and try again.
I'm confident that we fix this today.

**Comment by bspendrin** [comment]
Yes, it works now! Checked it with Eli and Mme Kahina and different items. :) Thank you so much for fixing it quickly!
