### ISSUE TITLE
Server is rapidly closing. 

### ISSUE THREAD

**Issue by Esdaught** [NiHoel/Anno1800UXEnhancer#24]
So, before writing this, i checked troubleshooting area, and nothing is fitting. Issue is, server is just closing after following
![anno](https://user-images.githubusercontent.com/101041496/156918250-2efd78de-5a18-4348-9da6-f41223ce4480.png)
Game, same as calculator, setted on russian (but there is 1 thing, hud is on russian, but dialogue is on english). I did some testing with server: almost same reaction if the game is not opened, difference is, there is no request recieved line, and server is just stuck; same reaction, if i launching server within main menu or already in the game. Sometimes the request recieved: lang=russian is doubling, but the result is just closing without anything.

**Comment by NiHoel** [comment]
Hello,

have you tried using the fallback files for older processors?
Does the crash also happen if you switch the game to English?
If it runs correctly, you should see several request received messages.

**Comment by Esdaught** [comment]
Ok, now it works. There is some strange text appears in server sometimes like this:
![Anno 2](https://user-images.githubusercontent.com/101041496/158342314-09188e11-261e-4049-9f1f-da6a60a516c2.png)
And calculator sometimes adds +1 to actual quantity of houses. But it's working and that's what matter. 
One small thing tho, it'll be nice, to see actual quantity in tons, when u managing trade routs and docs export, since u doing it manually (or i didn't digured it out, how to do it automatically). 
But ye, with that, u can close the issue, thanks for help!

**Comment by NiHoel** [comment]
The warning is from the text recognition since russian letters are quite different from the Latin alphabet.
For docklands, you can see the number of tons to import / export here: https://youtu.be/YxU-8YCzpec?t=621
For trade routes there is no such feature since one would need to know the travel times of all ships to calculated how much each one has to load to get the desired t/min.
