### ISSUE TITLE
Server instantly closes

### ISSUE THREAD

**Issue by TheRealUmbray** [NiHoel/Anno1800UXEnhancer#25]
Hi NiHoel

First of all, love the tool. Excellent work you have done here.

The issue I am excerpering is that the server closes as soon as it gets to try and run itself. The message I get is "Address 'HTTP://Localhost:8000/AnnoServer/Population is already in use" and then command promt closes itself. it happens so fast that the only way I could get the full message was by recording the process of starting the server.exe and freeze framing on the half a second the text is on screen. 

The issue appears to be intermittent, but I can't figure out what causes it, as it sometimes works after a reboot of my PC and sometimes doesn't. 

I have very limited programming understanding, so anything you need from me, let me know

**Comment by NiHoel** [comment]
Hello,

first of all you can open the console:
* right-clicking on the folder containing the Server.exe while holding shift
* Click Open Powershell window here (or something similar)
* Enter "./Server.exe" (without the quotes) to start it, even when it closes, you can still read the output messages

* Enter "./Server.exe -v" to get verbose output and paste it here 

* Make sure no other UXEnhancer is running (option one is sufficient): https://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/  (search for 0.0.0.0:8000)

**Comment by TheRealUmbray** [comment]
PS D:\Programmer (D)\Anno 1800 Calc> ./server.exe
Address 'http://localhost:8000/AnnoServer/Population' is already in use
PS D:\Programmer (D)\Anno 1800 Calc> ./server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load skyscrapers.
Load texts.
Address 'http://localhost:8000/AnnoServer/Population' is already in use
PS D:\Programmer (D)\Anno 1800 Calc>

It appears that the software for my keyboard is also listening to port 8000, and once I closed it down everything looks like it's working. So it appears I have found a workaround thanks to the troubleshooting steps. I don't know if this is anything you can improve upon the calculator based on.

**Comment by NiHoel** [comment]
You can use the -p argument to specify a different port, e.g. "./Server.exe -p 7999"
But then you have to modify the calculator: Search for      this.url = 'http://localhost:8000/AnnoServer/Population'    in AnnoCalculator.js and replace 8000 by 79999.
