### ISSUE TITLE
Assetviewer Link falsch

### ISSUE THREAD

**Issue by TKB001** [NiHoel/Anno1800UXEnhancer#26]
Hi,
erstmal vielen Dank für all die Mühen für die einzelnen Programme.
Der Link beim Assetviewer führt zu einem nicht (mehr?) vorhandenen Commit, so dass das Programm leider nicht compiliert werden kann.
Der Austausch auf andere Commits führt ebenfalls zu Fehlern, weil sich wohl Datenstrukturen und/oder Methoden geändert haben.
Ich gehe davon aus, dass das Assetviewer-Repo nicht aktuell ist.

Gruß

Andreas

**Comment by NiHoel** [comment]
Bitte nutze den aktuellsten commit von hier, um den AssetViewer zu bauen: https://github.com/Miraak7000/AssetViewer
Da Veratversus nicht mehr so viel Zeit hat, ist mit Updates nur verspätet oder gar nicht mehr zu rechnen. Allerdings werden meine Releases im Regelfall eine aktualiserte Version beinhalten. Du kannst einfach die .exe in deinem Build-Ordner durch meine ersetzen (funktioniert, mache ich auch so).

**Comment by TKB001** [comment]
Danke,
das ersetzen des Submodules durch das Repo von Miraak7000 hat funktioniert, bis auf einen kleinen Fehler bezüglich des Hardcodierten PFades für das Icon vom UXEnhancer verlief das compilieren Problemlos.

Nochmal Danke für die schnelle Hilfe!

**Comment by Veraatversus** [comment]
also um ehrlich zu sein hab ich update 13 nicht mal mitbekommen so selten wie ich noch da bin.  wäre cool wenn ich einfach über discord benachrichtigt werde und dann versuche ich natürlich zeitnah meinen pflichten nach zu kommen ;)
