### ISSUE TITLE
Server not importing lumberjack's hut and sawmills

### ISSUE THREAD

**Issue by AndyTunnah** [NiHoel/Anno1800UXEnhancer#27]
Everything else seems to be fine, it's grabbing all info, but not for these 2, am I doing anything wrong ?

I seen mention of a discord server but can't find a link anywhere. Thanks!

EDIT: I wasn't opening them all thoroughly, I've figured it out now.

**Comment by auddie2015** [comment]
It took me a bit to figure that out myself. If you are on the info tab that is for all islands, It will do it with charcoal, clay, beef farm, and for me it also won't populate iron mines and their related factories. I also think it will keep using that tab until you settle a second island.

**Comment by NiHoel** [comment]
I keep this in mind when preparing the next release (will take some time though)

**Comment by auddie2015** [comment]
> 

For the time being, it's okay once you settle a second island. It would be very hard to account for productivity modifiers, news papers, and townhall/labor union cards. Any tweaking is done on a local level per island. I won't complain if you can make it happen but it seems like a daunting task to me!

**Comment by AndyTunnah** [comment]
I don't play anymore - I was playing it because I loved the loop of unlock>upgrade, and as soon as I hit the top level I didn't feel the need to play again. Felt like I got what I wanted out the game, if that makes sense.

Still though, this tool was a big part of the enjoyment I got out of the game.
