### ISSUE TITLE
Finance count Bug w

### ISSUE THREAD

**Issue by Luna1040** [NiHoel/Anno1800UXEnhancer#29]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/31060031/180613128-d4bdeee3-bf5c-49a6-8809-55ec18ab4f50.png">

When I use Chinese Language, the Finance building cannot count into my Calculator

but the Population works normal as well

I think may be there are someting wrong with the Image recognition for Chinese

**Comment by NiHoel** [comment]
Try this version: https://drive.google.com/drive/folders/1Vsy3kXGe11d28pISqR82VpaCGdZaNtyi?usp=sharing
Since Chinese has far more symbols than English, detection accuracy might not be as good as in the English version.
