### ISSUE TITLE
No rerollbot

### ISSUE THREAD

**Issue by anonymousse37** [NiHoel/Anno1800UXEnhancer#3]
Hi,

I've DL this package : https://github.com/NiHoel/Anno1800UXEnhancer/releases/tag/v4.2

- Following the instructions then 

<
[one-time setup] download, install (and reboot your computer afterwards): vc_redist
Run UXEnhancer.exe
Edit the counters to specify how many times you want to buy that item (9999 is the maximum count and equivalent to infinity).
Open the trade menu of a trader that sells one of the items you want. The bot will start buying / rerolling automatically
Hit 'Esc' to pause the bot and close the window
Tutorial
Thanks to Veraatversus for adopting the AssetViewer
>

- Setting everything as required but nothing happening when i open the shop
- Noticed in the YT tutorial the rerollbot.exe that you do not mention in the instructions and is missing from the package i have downloaded.

So what am i not doing properly ?

Kind regards and thank you for the job you have done.

**Comment by NiHoel** [comment]
Did you check the troubleshooting section in the Readme?

**Comment by anonymousse37** [comment]
I did check yes.
I dont know.
I open UXEnhancer, i set what i want to buy
I go back to the game
I open shop
Nothing happens.

**Comment by NiHoel** [comment]
Open the UXEnhancer in the console with verbose option:
Shift + right click on folder containing UXEnhancer.exe -> Open PowerShell Window -> Enter  "UXEnhancer.exe -v"
Configure and open the store
Close UXEnhancer while the store is open
Send me the console output + UXEnhancerConfig.json + debug_images

**Comment by anonymousse37** [comment]
Did it a second time from fresh unzip

http://www.mediafire.com/file/lkhhvvh35lxkgjn/debug.7z/file

**Comment by NiHoel** [comment]
Are you running it in a virtual machine?
What about fullscreen windowed?

**Comment by anonymousse37** [comment]
Are you running it in a virtual machine?
> Not running any VM on this host atm.

Is any other task running with a title of "Anno 1800" (e.g. file browser)?
> Had chrome with web pages opened titled with anno stuff

Does version v4.1 work?
> Havent found RTM version of 4.1 and i dont want to compile source to get binaries

What happens if you record the window of Anno 1800 using a standard screen capturing program (e.g. obs)?
> I do not use this this software to record video or printscreen so i dont know. But streaming with twitch is no problem for example or recording via nvidia experience

Anyway, what does tell the verbose ? Any hint ? 

[17:36:17.454574] Trader: 0, ship full: 1, has reroll button: 0
> Trader: 0 means no trader detected ?
> ship full: 1 or ship full: 0 ? Swaping both value, my boat is empty as you can see in the printscreen so...
> has reroll button : 0 means i guess the bot rerolled 0 time.
 
> trading_menu_title.png in the debug image is weird ?
The bot using this data to find relative positions ?

**Comment by Rabusch** [comment]
Mal auf deutsch, dur hast vergessen den Server zu starten.
Ok. you forgot to start the server.exe at first. sorry for my englisch.

**Comment by anonymousse37** [comment]
[one-time setup] download, install (and reboot your computer afterwards): vc_redist
Run UXEnhancer.exe
Edit the counters to specify how many times you want to buy that item (9999 is the maximum count and equivalent to infinity).
Open the trade menu of a trader that sells one of the items you want. The bot will start buying / rerolling automatically
Hit 'Esc' to pause the bot and close the window

According to this or the video, it is never mentionned to start server.exe in order to use the reroll bot. Any way, i tried it but result is the same. 

Server.exe was only mentionned for statistic purpose which im not interessed in.

**Comment by NiHoel** [comment]
The problem is that the screenshotting does not work properly. See https://github.com/NiHoel/Anno1800UXEnhancer/issues/3#issuecomment-621938072

In fullscreen mode, the screenshots are black and far too small. We need to get correct screenshots of the game.

**Comment by NiHoel** [comment]
At the moment, I have no idea why screenshotting of the application does not work in your case.

**Comment by NiHoel** [comment]
Can you replace the .exe of the latest release with this one:
[UXEnhancer.zip](https://github.com/NiHoel/Anno1800UXEnhancer/files/4560341/UXEnhancer.zip)

And try again with Anno in fullscreen mode?

**Comment by anonymousse37** [comment]
Only in full screen but it is supposed to work in windowed mode as well ?
Have you check the files i ve uploaded ?

**Comment by NiHoel** [comment]
Yes, the strange thing is that the screenshots capture the screen outside of the Anno application. This should not happen.

**Comment by NiHoel** [comment]
Did the program ever complain that it could not find Anno although Anno was open?

**Comment by anonymousse37** [comment]
no it didnt, in the verbose, can see it detects ships passing by. I have commercial roads with shit comming by to get stuff, i guess this is why i see ship:0 or ship:1 full 
Maybe a software is in conflict with yours.
The cursor is not moving at all.
Am i supposed to be on option menu before going to shop ?
So is server.exe supposed to be lauched ?

**Comment by NiHoel** [comment]
Server.exe is not relevant for you.

**Comment by anonymousse37** [comment]
ok ty, gon' try to use this release and i ll tell you.
What resolution am i supposed to run with 4.1 ?

**Comment by NiHoel** [comment]
Unless trader /= 0 nothing will happen. The program relies on a correct screenshot. Otherwise it checks the wrong locations for information -> nothing happens.

**Comment by NiHoel** [comment]
Try the file I send you above together with 4.2 (you currently have) first.

**Comment by anonymousse37** [comment]
Sorry, what do you mean ?
copy paste the files you sent me to 4.2 ?
Try the file I send you above together with 4.2 (you currently have) first.

**Comment by anonymousse37** [comment]
When closing the soft have this at the end of the log. Dunno if this is relevant.

e(
00007FF6C0E94680)::~ObjectCache(): WARNING! LEAK! object 000001D322ADA420 still has count 1 (id 
C:\Users\IDIOT\Downloads\Anno1800UXEnhancer_v4.1/tessdata/fra.traineddatalstm-number-dawg)

**Comment by anonymousse37** [comment]
i did replace the exe from 4.1 to 4.2
started the soft with verbose and anno in full screen, still having black screen xD
Are you using a 3rd party software to printscreen or the native windows function ?
Wondering if it could be in conflict with another program installed on my computer

**Comment by anonymousse37** [comment]
https://superuser.com/questions/1353146/windows-10-screenshot-black-multiple-tools-standard-greenshot-snipping-tool

Have a 1080Ti FTW3 + i7 8086k@5Ghz, i dont know how the HW could be a problem.
Maybe the nvidia drivers.
Weird thing is using the native printscreen function of windows is not giving me a black print screen.

Maybe i should try on a new game, this one is a 250 hours game and the game crash sometimes.
Its a known issue at ubisoft but they arent able to solve it. It still in progress after one year.
It happens with 50 hours+ games.

**Comment by anonymousse37** [comment]
Ok found the solution.
you gon' laugh.
The game has to be set on windowed full screen in option/graphic/window mode
you might want to disable DVR from XBOX native shit stuff delevered with windows.
you should add this in the prerequisites in your tutorial.
dunno how many ppl used you soft but cant believe no one had this issue.
anyway, thank you for the job you've done and the provided help.
can now stuff my 300+ trade boats painlessly =)

**Comment by NiHoel** [comment]
Thanks, I added it in the readme.

The reward pool depends on the destination of the expedition:
https://www.reddit.com/r/anno/comments/ewbgzb/anno_1800_expeditions_keep_yielding_the_same/fg0yd8j/?context=3

and here https://forums-de.ubisoft.com/showthread.php/220922-Expeditionen-%E2%80%93-Auflistung-aller-Belohnungen-nach-Schwierigkeit-und-Region?p=2687865&viewfull=1#post2687865 (in german, but with the translation help from AssetViewer you should get the information you need)

**Comment by anonymousse37** [comment]
Awesome bro, thank you for the tip !
This is confusing cause i tho i would get them from artic expedition since they used to live in there but according to ubisoft, better chance to find them in other regions xD.
Make sense !
