### ISSUE TITLE
Wolkenkratzer werden nicht korrekt berrechnet

### ISSUE THREAD

**Issue by rolaran** [NiHoel/Anno1800UXEnhancer#30]
Hey Nihoel,

erstmal danke für den tollen Rechner. Ich nutze den jetzt schon einige Zeit in meinen Games :).

Ich habe heute das erste mal das den neuen DLC gestartet und hab deinen Rechner lokal aktualisiert. Allerdings ist es so, dass er bei der Crown Falls City die Wolkenkratzer falsch berechnet. Er setzt vor jede Einheit die jeweilige Stufe als zusätzliche Zahl davor. Bedeutet Ich habe ingame 146 Ingenieure Stufe 1. Im Calculator zeigt er mit 1146 an. Gleiches Spiel bei Investoren und unabhängig von der Stufe. Jetzt hab ich lt. Calculator natürlich einen enormen Malus :).

Hab ich da etwas falsches eingestellt?

Danke und lG
Rolaran
![ingenieure_calculator](https://user-images.githubusercontent.com/59846280/194893056-f7779d85-ca24-42ad-a4ff-585373862b6e.PNG)
![wolkenkratzer](https://user-images.githubusercontent.com/59846280/194893079-74fc7e39-b585-4f3c-83e7-c1144318cd1f.PNG)

**Comment by NiHoel** [comment]
Ich brauche die Screenshots des Servers, um nachvollziehen zu können, was schief läuft.

**Comment by rolaran** [comment]
Ok kommen heute Abend oder spätestens morgen. Danke schonmal

**Comment by rolaran** [comment]
Hey Nihoel,

hilft dir der Screenshot des Servers?

![image](https://user-images.githubusercontent.com/59846280/195002922-83e38644-e22b-405c-9351-06028620c316.png)

Das Problem ist eben dass ich nur 146 Wolkrenkratzer auf Stufe 1 von den Ingenieuren habe. Er setzt also den 1er von Stufe 1 vor die Anzahl der Gebäude und macht daraus 1146. Selbes Spiel bei Stufe 2. Da werden aus 50 Gebäuden 250 usw.

**Comment by NiHoel** [comment]
Leider nein,

ich brauche den Inhalt des Ordners "debug_images".

**Comment by rolaran** [comment]
Sehr gerne. Bitteschön

https://drive.google.com/file/d/1lqUVX1aULAr-bxWW6Sw3HKED_fukrQKX/view?usp=sharing
