### ISSUE TITLE
Beta u16 Calculator and UXEnhancer

### ISSUE THREAD

**Issue by auddie2015** [NiHoel/Anno1800UXEnhancer#33]
I am trying out your beta calculator from the link you provided in the issues section of that repo. Server.exe doesn't recognize the calculator. Is there a beta UX to go with the calculator? If not, I am in no rush to dive into Artistas or new lifestyles so the 20 Sept calculator is fine.

**Comment by NiHoel** [comment]
Connection to the server is intentionally turned off and needs some testing and updating.
I plan to release an update for calculator and UXEnhancer within the next week.

**Comment by auddie2015** [comment]
Thanks! I am not a big fan of the lifestyles so the people can wait. (Forever lol)

Maybe not the place to ask but is there a Patreon or Ko-fi?
