### ISSUE TITLE
Rerollbot bot 10.1 not work

### ISSUE THREAD

**Issue by hjklwrbhkysbdfyaejtrj** [NiHoel/Anno1800UXEnhancer#34]
[debug_images.zip](https://github.com/NiHoel/Anno1800UXEnhancer/files/10476191/debug_images.zip)
[debug_images3.zip](https://github.com/NiHoel/Anno1800UXEnhancer/files/10476197/debug_images3.zip)
[debug_images2.zip](https://github.com/NiHoel/Anno1800UXEnhancer/files/10476204/debug_images2.zip)

**Comment by NiHoel** [comment]
I'll have a look at it next weekend.

**Comment by hjklwrbhkysbdfyaejtrj** [comment]
v10 don't work either

**Comment by NiHoel** [comment]
Does it work, if you replace those two files?

[UXEnhancer_Patch_v10.1.1.zip](https://github.com/NiHoel/Anno1800UXEnhancer/files/10522848/UXEnhancer_Patch_v10.1.1.zip)

**Comment by hjklwrbhkysbdfyaejtrj** [comment]
it work now. click refresh before buying
