### ISSUE TITLE
How to slow down reroll bot?

### ISSUE THREAD

**Issue by jugularvein** [NiHoel/Anno1800UXEnhancer#35]
How can I slow down reroll bot so that it only rolls once every 2 seconds?

Bot is clicking roll so fast that it is buying the wrong item. It was to buy an item then rolls and clicks the spot where that item would have been.

**Comment by NiHoel** [comment]
Did you check that the bought item is not in your list (or one with the same price)?

If not, then follow the debugging instructions and send me the files. The refresh of your game would have to be very slow (> 400 ms after click) to be the cause of this error.
