### ISSUE TITLE
little mistake in your readme.md deletes settings

### ISSUE THREAD

**Issue by EvaBronson** [NiHoel/Anno1800UXEnhancer#4]
for the max reroll costs you are missing the "quotation marks" in your readme.
just copying the code deleted my item list a few times before i noticed. its quite a good feature and i guess most people wont get it working ;)

{
    "settings": {
    	"maxRerollCosts": "1000000"   // over here
        "language": "english"
    },
    ...
}

**Comment by NiHoel** [comment]
Thanks for the remark, the comma was missing.

**Comment by EvaBronson** [comment]
na, its still wrong^^

the 1000000 has to be inside " "
without quotation marks it will just recreate a clean config.

**Comment by NiHoel** [comment]
For me it works fine, with or without quotation marks.

**Comment by Pharamond** [comment]
I can confirm this.
this Works:

> {
    "settings": {
        "language": "german",
        "maxRerollCosts": "250000"
    },

> 
Have a Nice Day
And Thx for your Great Job
