### ISSUE TITLE
Buying a book for Eli will buy all Books

### ISSUE THREAD

**Issue by Baardaapje1** [NiHoel/Anno1800UXEnhancer#5]
Since the last update I have the following issue:
I'm buying books for Eli: Captains of Industry and VOL XXXI and Contracception Regulation. Since the last update the UXEnhancer buys any Epic Book from Eli when Vol XXXI is on and buys any Rare book when Contraception Regulation is on.

Also, when buying an Epic book it will deducte the amount of books from Captains of Industry, so it looks like th UXEnchancer "thinks" that it bought that book but in real it bought another book. The same goes from Contraception Regulation.

In the attachment you can find a screenshot. On the left the items which the UXEnchancer should buy, on the right a screenshot from an item it just bought. Note: this bug only seems to appear on books.

I've allready deleted the UXEnhancer, downloaded the latest version and re-installed it, but didn't work. In the attachement you can also find the Config file.
[UXEnhancerConfig.zip](https://github.com/NiHoel/Anno1800UXEnhancer/files/4735700/UXEnhancerConfig.zip)
![Screenshot](https://user-images.githubusercontent.com/66472238/83870392-7b77bb80-a72e-11ea-854b-375669a79b21.png)

**Comment by NiHoel** [comment]
Unfortunately, I could not reproduce the bug.
Did it occur often? -> If it occurred just once or twice, then ignore it.
Otherwise follow the instructions in Readme under "If you encounter a bug ..."
