### ISSUE TITLE
Server does not work

### ISSUE THREAD

**Issue by Fwd85** [NiHoel/Anno1800UXEnhancer#9]
Hello,
the server is not working for me.

"the ingame text language and the language of the calculator/bot config are identical"
Yes both are german.

"the values to be read are not covered by something else (overlay, external program, etc.; basically things you would see when running a screen capturing program)"
No external programs running.

"The window mode of the game is set to 'windowed full screen'"
Anno runs in windowed full screen.

"Disable XBOX DVR"
Is disabled

"(Statistics Extractor) the correct island is selected in the statistics screen"
Yes

"(Statistics Extractor) the island has a long (> 8 letters) name composed from standard letters (A-Za-z) and with other islands as few characters in common as possible"
Name of the island is "Goutelaire"

"(Statistics Extractor) in the center of the statistics menu the selected entry is fully visible"
Yes it is all visible.

Further info:
Win 10 Ver 2004
Anno 1800 Ver 14.34679.0.2790
VC_redist.x64 and VC_redist.x86 installed
Screen resolution 1920x1200

**Comment by NiHoel** [comment]
Hello,

can you start the verbose mode as described in the readme and send me the files?

**Comment by Fwd85** [comment]
I hope this is what you want.
[test.txt](https://github.com/NiHoel/Anno1800UXEnhancer/files/5405356/test.txt)

**Comment by NiHoel** [comment]
Please send me the images from debug_images. Otherwise I cannot judge what should be the output.

**Comment by Fwd85** [comment]
How do I do this? I Can not find something like debug_images.

**Comment by NiHoel** [comment]
A new folder debug_images should be created next to the .exe when you start it using Server.exe -v

If it does not appear send me some ingame screenshots (at least of each tab) of the statistics menu.

**Comment by Fwd85** [comment]
PS C:\Users\Sven\Desktop\Anno1800UXEnhancer_v4.3> .\Server.exe -v
Load sessions and regions.
Load factories.
Load population levels.
Load texts.
Listening for requests at: http://localhost:8000/AnnoServer/Population
Press ENTER to exit.
request received: lang=german
Update tesseract.

Update tesseract.
detected resolution: 1920x1200
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: SENSE N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DE N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DEAN
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DAN ER N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: GEDAANE Ôé¼ N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DATEN
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DAEE RAN
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DATE IS
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DAN EN N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: PEN N
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DAN Ôé¼ a
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DEE. Ôé¼ Na
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DE NS
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DANN I
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: All Islands
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: NE Ôé¼ AS
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DANN,
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DANN WE
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DENE NR
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: en
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: DET VO
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: BE ANEEA W
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: GERNE WE
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: ZENE N WS
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: BER SE
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island: ER SE
request received: lang=german
Update tesseract.

Update tesseract.
can't find population
Island:

![screenshot_2020-10-20-23-34-13](https://user-images.githubusercontent.com/21112328/96647206-8cb41400-132d-11eb-9f6f-a36b15fafe0d.jpg)
![screenshot_2020-10-20-23-34-22](https://user-images.githubusercontent.com/21112328/96647208-8d4caa80-132d-11eb-9172-4c3e4ecca721.jpg)
![screenshot_2020-10-20-23-34-27](https://user-images.githubusercontent.com/21112328/96647214-8e7dd780-132d-11eb-96e0-2e7babf98247.jpg)
![screenshot_2020-10-20-23-34-31](https://user-images.githubusercontent.com/21112328/96647217-8f166e00-132d-11eb-88ee-e76aad136340.jpg)
![screenshot_2020-10-20-23-34-39](https://user-images.githubusercontent.com/21112328/96647218-8faf0480-132d-11eb-99e9-16bd64f97376.jpg)

**Comment by NiHoel** [comment]
The issues are the borders (top and bottom) of the menu. Since my detection boxes are relative to a full screen image, they do not work here. I will take care of it with the next update for GU 9.

**Comment by Fwd85** [comment]
Nice to hear. Thanks for your work.
